### ISSUE TITLE
Motion

### ISSUE THREAD

**Issue by EtienneDepaulis** [obie/guide-to-reactive-rails#4]
This issue is more a question: everyone talks about StimulusReflex (which is really good at marketing) but [motiong](https://github.com/unabridged/motion) does quite the same thing.

I've been playing with both and I find motion API to be easier to use (it is closer to PhoenixLiveView in my opinion).

I'm having trouble understanding the differences between those 2 gems and would love to have a comparative article about those 2 gems cc @alecdotninja @hopsoft

My goal is not to decide which one is the best, I truly think that the reactive rails approach is awesome. As a developer, I'm having trouble deciding on which horse to invest :)

Thanks for your time

**Comment by obie** [comment]
My impression is that SR not only has better marketing, but is also more flexible because it doesn't force you to use components. But yes, an article would probably be useful.
